### ISSUE TITLE
bundles can be nested in each other allowing for infinite item storage

### ISSUE THREAD

**Issue by NyanMC** [Cheaterpaul/BetterBundles#2]
in vanilla bundles can be nested inside each other, however the nested bundle has a "weight" of all of the items it contains +4 as to not allow for infinite storage. these bundles have a fixed weight of 64, allowing for infinite bundle nesting and in turn infinite storage
steps to reproduce:
get a copper+ tier bundle (let's call this bundle 1) and fill it with items
get a second copper+ tier bundle (let's call this bundle 2) and place bundle 1 inside of bundle 2
fill the remaining space in bundle 2 with items
you can repeat the last two steps infinitely for infinite space
![image](https://user-images.githubusercontent.com/44331238/148479026-74fa3ac8-ea3e-423e-9afd-b22634b56b2d.png)

to fix this, you can either blacklist tiered bundles from going into each other, or use vanilla calculations for bundle weights

**Comment by Cheaterpaul** [comment]
Thanks for reporting so detailed.

Is fixed in version 1.0.3

This issue was caused, because i checked only for the vanilla bundle on insert and not for the tiered bundles.
