### ISSUE TITLE
Right clicking on a stack with a bundle that already has over a stack of items in it does not put all the items in it

### ISSUE THREAD

**Issue by PORTB** [Cheaterpaul/BetterBundles#4]
Right clicking on a stack of items with a bundle that already has items in it does not put all the items from the stack that was clicked on into the bundle, despite there being enough room
[https://streamable.com/7qdr78](https://streamable.com/7qdr78)

**Comment by Cheaterpaul** [comment]
should be fixed with the new 1.0.5 version
