### ISSUE TITLE
BetterBundles does not load on 1.18.2 do to no "net/minecraftforge/common/Tags$IOptionalNamedTag"

### ISSUE THREAD

**Issue by ghost** [Cheaterpaul/BetterBundles#6]
it looks like a Class it trying to use got removed
Logs and what not:
[latest.log](https://github.com/Cheaterpaul/BetterBundles/files/9701444/latest.log)
[crash-2022-10-03_18.13.09-fml.txt](https://github.com/Cheaterpaul/BetterBundles/files/9701445/crash-2022-10-03_18.13.09-fml.txt)

**Comment by Cheaterpaul** [comment]
fixed in the latest beta version
